In [67]:
import numpy as np
from numpy.random import randint

In [68]:
randint(2,10)

7

In [69]:
my_list = [1,2,3]


arr = np.array(my_list)
arr

array([1, 2, 3])

In [70]:
my_list2 = ([1,2,3],[4,5,6],[7,8,9])
np.array(my_list2)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [71]:
np.arange (0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [73]:
np.zeros (3)

array([0., 0., 0.])

In [74]:
np.zeros ((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [75]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [76]:
# np.ones(5)

In [77]:
np.linspace(0,5 , 10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [78]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [79]:
np.random.rand(5)

array([0.28886642, 0.94805957, 0.41598055, 0.31724231, 0.19818831])

In [80]:
# np.random.randn((5,5))

In [81]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [82]:
# ranarr = np.random.rantint(0,50,10)

In [83]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [84]:
# ranarr.max(49)