In [2]:
import numpy as np 

In [4]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
arr[9]

9

In [9]:
arr[1:5]

array([1, 2, 3, 4])

In [11]:
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [13]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
slice_of_arr = arr [0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [16]:
slice_of_arr[:]=99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [20]:
arr_2dm = np.array ([[5,10,15],[20,25,35],[35,40,45]])


In [21]:
arr_2dm

array([[ 5, 10, 15],
       [20, 25, 35],
       [35, 40, 45]])

In [28]:
arr_2dm[1][1]

25

In [54]:
arr_2dm [2][1]



# [2] is rows 
# [1] is column

40

In [29]:
arr_2dm[:2]

array([[ 5, 10, 15],
       [20, 25, 35]])

In [30]:
arr_2dm[1:]

array([[20, 25, 35],
       [35, 40, 45]])

In [31]:
arr_2dm[:2,1:]

array([[10, 15],
       [25, 35]])

In [35]:
arr = np.arange (1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [44]:
bool_arr = arr >5
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [45]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [47]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [48]:
arr[arr<3]

array([1, 2])

In [51]:
arr_2d = np.arange(50).reshape(5,10)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [58]:
arr_2d[1:3, 3:5]

array([[13, 14],
       [23, 24]])